### ISSUE TITLE
GNN default edge attributes wrong

### ISSUE THREAD

**Issue by gmertes** [ecmwf/anemoi-training#22]
### What happened?

The edge attributes in the default GNN config are wrong. The debug config (which has the GNN as default) crashes with:

```
Error in call to target 'anemoi.models.layers.processor.GNNProcessor':
KeyError('edge_length')
```

### What are the steps to reproduce the bug?

`anemoi-training train --config-name=debug`

### Version

develop

### Platform (OS and architecture)

all

### Organisation

ECMWF

**Comment by anaprietonem** [comment]
Hey Gert! just in case it's helpful, we had this issue last week (both with the `gnn` and with the `graphtransformer`). With Mario's help we managed to get it working by:
1. changing the graph type from:` - graph: default` -> `- graph: multi_scale`
2. inside graph/multi_scale.yaml
change:
```
    edge_builder:
      _target_: anemoi.graphs.edges.TriIcosahedralEdges
      xhops: 1
```
to:
```
    edge_builder:
      _target_:  anemoi.graphs.edges.MultiScaleEdges
      x_hops: 1
```

Probably @JPXKQX can add more to this!

**Comment by theissenhelen** [comment]
Anemoi-graphs only features MultiScaleEdges which combines the use cases for TriNodes and HexNodes. 

I found another bug in the graph cleaning, which I addressed in https://github.com/ecmwf/anemoi-graphs/pull/33.

**Comment by JPXKQX** [comment]
Exactly! When we change the architecture to `gnn` or `graphtransformer`, we do not pass edges to the processor, and when we look for the attributes, it fails. Now, with [PR #24](https://github.com/ecmwf/anemoi-models/pull/24), better errors are provided. 

As for graph cleaning, it is fixed in the develop branch of anemoi-graphs, but not yet released.
